baseurl: /
markdown: Redcarpet
markdown_ext:  markdown,mkd,mkdn,md
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "footnotes","space_after_headers","highlight","underline","quote","lax_spacing"]
permalink: /:year/:month/:day/:title/
author: HyperHu
pygments: true
safe: true
paginate: 16
auto: true

